F_function_vectorized(LLR[0][7].data(), LLR[0][6].data(), 64);
F_function_vectorized(LLR[0][6].data(), LLR[0][5].data(), 32);
G_function_0R_vectorized(LLR[0][5].data(), LLR[0][4].data(), 16);
G_function_0R_vectorized(LLR[0][4].data(), LLR[0][3].data(), 8);
RepSPC_8(LLR[0][3].data(), BitPtr+24);
Combine_0RSimple(BitPtr+16, 8);
Combine_0RSimple(BitPtr+0, 16);
G_function_vectorized(LLR[0][6].data(), LLR[0][5].data(), BitPtr+0, 32);
F_function_vectorized(LLR[0][5].data(), LLR[0][4].data(), 16);
F_function_vectorized(LLR[0][4].data(), LLR[0][3].data(), 8);
Repetition_vectorized(LLR[0][3].data(), BitPtr+32, 8);
G_function_vectorized(LLR[0][4].data(), LLR[0][3].data(), BitPtr+32, 8);
RepSPC_8(LLR[0][3].data(), BitPtr+40);
CombineSimple_vectorized(BitPtr+32, 8);
G_function_vectorized(LLR[0][5].data(), LLR[0][4].data(), BitPtr+32, 16);
F_function_vectorized(LLR[0][4].data(), LLR[0][3].data(), 8);
RepSPC_8(LLR[0][3].data(), BitPtr+48);
P_RSPC(LLR[0][4].data(), BitPtr+48, 8);
CombineSimple_vectorized(BitPtr+32, 16);
CombineSimple_vectorized(BitPtr+0, 32);
G_function_vectorized(LLR[0][7].data(), LLR[0][6].data(), BitPtr+0, 64);
F_function_vectorized(LLR[0][6].data(), LLR[0][5].data(), 32);
F_function_vectorized(LLR[0][5].data(), LLR[0][4].data(), 16);
F_function_vectorized(LLR[0][4].data(), LLR[0][3].data(), 8);
Repetition_vectorized(LLR[0][3].data(), BitPtr+64, 8);
G_function_vectorized(LLR[0][4].data(), LLR[0][3].data(), BitPtr+64, 8);
F_function(LLR[0][3].data(), LLR[0][2].data(), 4);
Repetition(LLR[0][2].data(), BitPtr+72, 4);
P_R1(LLR[0][3].data(), BitPtr+72, 4);
CombineSimple_vectorized(BitPtr+64, 8);
P_RSPC(LLR[0][5].data(), BitPtr+64, 16);
P_RSPC(LLR[0][6].data(), BitPtr+64, 32);
CombineSimple_vectorized(BitPtr+0, 64);
